### ISSUE TITLE
Cached file just get delivered at the 3th call

### ISSUE THREAD

**Issue by M4rt1n17** [lochmueller/staticfilecache#149] opened 2019-04-29 20:33 UTC
## Bug Report

**Current Behavior**
When I clear all caches and call my site. At the 3th call I get delivered a cached site.
I'm coming from 6.1.2, there I got a cached page delivered at the 2th call.

When the Page is cached in the Backend I get a cached page everytime. But the first User after clearing/flushing Caches needs 3 calls to get delivered a cached page. befor it was 2.

**Expected behavior/output**
Delivering a cached Page at the second call.

**Environment**
- TYPO3 version(s): 9.5.5
- staticfilecache version: 8.0.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Comment by lochmueller** [comment] 2019-04-29 20:41
Hey @M4rt1n17 
perhaps TYPO3 send a header that the second call is not send to the server? Do you checked in the access log if all 3 calls are handled by the server (independant if the page is deliverd via cache or not).
Regards,
Tim

**Comment by lochmueller** [comment] 2019-04-30 09:45
Also check, if the cache is generated at the first or second hit.

**Comment by M4rt1n17** [comment] 2019-05-01 18:17
I debuged it and its seems the Cache gets generated by the second hit.
I would expext it to be generated at the first (and also delivered at the first hit).

Hope thats helps. 

Thanks btw for the new htaccess, the old one from v6 wasnt by default compatible with TYPO3 9, but this now is!

Is there a way to autoinclude the htaccess file after activating the extension, and to exclude it after deactivating it?
Would make things more clean. In Wordpress this is possible, but I will watch out for a TYPO3 Extension which maybe does this so this mechanism can be implemented here maybe too.

**Comment by lochmueller** [comment] 2019-05-01 19:04
Hey @M4rt1n17 
it is not possible to generate and deliver the cache in one request (technical).

Generation at the second hit sound strange. I think the first call to not deliverd by the server (perhaps some Expires Headers oder Cache-Control headers / e.g. if you reload a page in the browser, the browser send Cache Control headers).

I think it is not possible to handle this task via github at the moment (many variables in the process). Could you send some details related to the test szenario?

`Is there a way to autoinclude the htaccess file after activating the extension, and to exclude it after deactivating it?` hmm.... only with magic string replace. Problem would be: if there is any error in the string replacement the website is down (server 500 error) and the "normal user" could not deactive the extension again. So I suggest to add the configuration manually to the htaccess file.

Perhaps check in the backend module if there are any "Static File Cache" related rules part of the htaccess file and display a warning, if the rules are missing. But this is als difficult, because there are users, that add the rules to the apache configuration and not to the htaccess :-/

Regards,
Tim

**Comment by M4rt1n17** [comment] 2019-05-09 12:53
Hi again,

ah ok, I tought its possible to let the user wait untll the request is cached, then fire out (at the first request) the cached version. In Wordpress (WP-Rocket this works) thats maybe the reason I tought its also working here.

Including this htaccess feature would be nice at least for TYPO3 as your htaccess is working out of the box without any errors, but if its to risky I can understand this,

Best regards, Martin

**Comment by lochmueller** [comment] 2019-05-09 21:24
"I tought its possible to let the user wait untll the request is cached" this is only possible if you wait in PHP and deliver the staticfilecache. But this is not the "use case" of staticfilecache because there is no delivery logic in PHP in EXT:staticfilecache. The complete delivery is handled by htaccess and the files system only. I think it is technical not possible to wait in Apache (htaccess) context for a separate PHP request.

I will check this in WP-Rocket.

Regards,
Tim

**Comment by chesio** [comment] 2019-05-10 11:24
> Including this htaccess feature would be nice at least for TYPO3 as your htaccess is working out of the box without any errors, but if its to risky I can understand this,

As Tim said, every change to `.htaccess` file bears a risk of breaking the site entirely. WordPress core itself, when updating the `.htaccess` file, does a subrequest to test if the site still works after the change and eventually roll-back the changes in case of error.

I'm not sure if such complex handling should be added to otherwise simple caching plugin. Besides, I found it good to get to know your `.htaccess` file well on many occasions.

But that's just my 2 cents :-)

**Closed** 2019-05-10 11:57 UTC

**Comment by lochmueller** [comment] 2019-05-10 12:00
I think this is annoying to integrate. Perhaps this should be a core function to secure modify .htaccess files (also for e.g. redirects etc.). I pushed a check of the htaccess file and add the result to the "configuration" backend view as hint. If there is no "SFC_FULLPATH" in the htaccess file there will be a small warning.

I cannot reproduce the problem of the 3rd call cache describe in the ticket. I think this is a problem of the test scenario. Feel free to add integration tests for this so it is easy to rebuild. The issue is closed for the moment...
