### ISSUE TITLE
v.12.5.0 parse Error in Configuration.php on line 51, BackendController.php on line 27

### ISSUE THREAD

**Issue by birgitberlin** [lochmueller/staticfilecache#368] opened 2022-09-28 15:55 UTC
PHP Parse error:  syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/clients/client20/web1643/web/typo3conf/ext/staticfilecache/Classes/Configuration.php on line 51

-> line should be deleted

PHP Parse error:  syntax error, unexpected 'QueueService' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/clients/client20/web1643/web/typo3conf/ext/staticfilecache/Classes/Controller/BackendController.php on line 27

-> line should be deleted

Tested in TYPO3 10.4.32 an PHP 7.4.9

**Comment by lochmueller** [comment] 2022-09-28 16:29
Hey @birgitberlin ,
the minimum PHP requirement is 7.4 and typed properties are part of PHP 7.4: https://stitcher.io/blog/typed-properties-in-php-74
I think you execute the extension with an older/EOL PHP version?! 
Regards,
Tim

**Comment by lochmueller** [comment] 2022-09-28 16:32
@birgitberlin 
Notice: Do you get the error on CLI (because Configuration ist part of the ext_* files) or via web request? If it is a CLI request, you execute the command with PHP < 7.4?
Regads,
Tim

**Comment by lochmueller** [comment] 2022-10-28 11:08
Hey @birgitberlin 
I close this issue. The problem is related to an old PHP Version, because there are no syntax problems in these lines.
I suggest to check, which PHP version is executed in this context.
Regards,
Tim

**Closed by lochmueller** 2022-10-28 11:08 UTC
