### ISSUE TITLE
root index.html overwritten by subpage index.html in rare cases.

### ISSUE THREAD

**Issue by bibusdax** [lochmueller/staticfilecache#181] opened 2019-09-02 07:44 UTC
## Bug Report

**Current Behavior**
Today in our TYPO3 cms the page https://www.bibus.de was showing the content of https://www.bibus.de/produkte-loesungen/pneumatik/produkte-fuer-wasser/durchfluss-sensoren/ckd-serie-wfk3000-fuer-wasser/
It seems when that page was called, due to some unexpected race condition, the path got lost and index.html was saved in the root instead of its appropriate position.

**Expected behavior/output**
I expect the root page of a site always to show only the content of the root page
So https://www.bibus.de should show the startpage of that environment.

**Environment**
- TYPO3 version(s): 9.5.9 patched
- staticfilecache version: 9.0.0 patched
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: CentOS 7.5

**Possible Solution**

There is obviously a race condition where the path information may get lost or is not retrieved.
There needs to be a safety check in the code to ensure that no index.html is being written, if there is no path information and if it is not a root page.

**Additional context**
Add any other context about the problem here
Some months ago, I think with version 6.2, I had a similar issue.

**Comment by lochmueller** [comment] 2019-09-10 08:21
Hey @bibusdax 
thanks for the request. The problem is, that this race conditions are hard to find. It is possible that any other process build the TSFE and fake the frontend request (That is the reason for this rule: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/Rule/NoFakeFrontend.php ) .... So I need a deeper look into this problem. Do you have some logs? Do you enabled the logging for static file cache and get some information out of that?
Regards, Tim

**Comment by lochmueller** [comment] 2019-09-26 13:32
I close this issue. I prepare version 10 at the moment. Please send me more feedback, if I should look deeper into this. The new version of StaticFileCache use the Middleware mechanism. Should be much easier to handle such problems then.

**Closed by lochmueller** 2019-09-26 13:32 UTC
