### ISSUE TITLE
Page does not load in specific browser when using the home page as a shortcut. 

### ISSUE THREAD

**Issue by sebastiangaertner** [lochmueller/staticfilecache#213] opened 2019-11-04 08:54 UTC
I can not open the startpage (its a link into page ID 5 ) is that a known problem. It only happens with Safari browser. Weirdly enough Chrome can open the page. 
s.

**Comment by lochmueller** [comment] 2019-11-04 11:55
Hey @sebastiangaertner 
do you have some more details and usefull information? Error messages, log information, screenshot, headers... Could you confirm that the problem is part of the generated cache file of StaticFileCache?
Regards,
Tim

**Comment by lochmueller** [comment] 2019-11-06 21:58
Hey @sebastiangaertner 
I close this issue. I need some more information and the relation to StaticFileCache. Feel free to reopen the issue incl. Screenshots, error description, log information.
Regards,
Tim

**Closed by lochmueller** 2019-11-06 21:58 UTC
