### ISSUE TITLE
Boost mode seems with TYPO3 9.5 not working

### ISSUE THREAD

**Issue by brotkrueml** [lochmueller/staticfilecache#109] opened 2018-11-15 06:42 UTC
## Bug Report

**Current Behavior**
I activated the boost mode in the extension's settings. I flush the frontend caches, the file is still available in file system under typo3temp, Now I point my browser to the website a new generated page is delivered instead of the stored file (looking at the generated time in the source code).

**Expected behavior/output**
The (old) page from file cache should be delivered to the client as long as the scheduler task did not run.

**Environment**
- TYPO3 version: 9.5.1
- staticfilecache version: 6.1.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Ubuntu 16.04 with PHP 7.2.12

**Additional context**
My extension configuration:

    'staticfilecache' => [
        'backendDisplayMode' => 'current',
        'boostMode' => '1',
        'cacheTagsEnable' => '0',
        'cacheTagsHeaderName' => 'X-Cache-Tags',
        'clearCacheForAllDomains' => '0',
        'disableInDevelopment' => '0',
        'enableStaticFileCompression' => '0',
        'fileTypes' => 'xml,rss',
        'htaccessTemplateName' => 'EXT:staticfilecache/Resources/Private/Templates/Htaccess.html',
        'recreateURI' => '0',
        'saveCacheHook' => 'InsertPageIncache',
        'sendCacheControlHeader' => '1',
        'sendCacheControlHeaderRedirectAfterCacheTimeout' => '0',
        'sendHttp2PushEnable' => '0',
        'sendHttp2PushFileExtensions' => 'css,js',
        'sendHttp2PushFileLimit' => '10',
        'sendTypo3Headers' => '0',
        'showGenerationSignature' => '1',
        'strftime' => '%Y-%m-%d %H:%M',
    ],

**Comment by lochmueller** [comment] 2018-11-18 00:25
Hey @brotkrueml 
I tried to rebuild the problem, but it works great in my TYPO3 9.5 installation. The problem is: If the file exists, why the user request should go to TYPO3 and not in the cache file?!? There is no reason (exept a BE login?!). Do you have a "be cookie"?
Regards,
Tim

**Comment by M4rt1n17** [comment] 2018-11-22 06:54
For me its also not working properly in 9.5.x
If I was logged in and the Backend-Cookie is set I cant reload my page.
If I delete the Cookie everything is working fine.

To reproduce: 
1.) log in
2.) close browser
3.) open browser and open your site (this works)
4.) reload (then you see the error)

**Comment by lochmueller** [comment] 2018-11-22 15:52
@M4rt1n17 But this is a reagular process. If the Backend Cookie exists, StaticFileCache will not deliver the static Frontend and will not generate a new Entry.

**Comment by lochmueller** [comment] 2018-12-21 07:47
Hey @M4rt1n17 
I close this issue. If there are any news or technical details, we can reopen the problem.
But at the moment I cannot rebuild it in 9.5.x installations.
Regards,
Tim

**Closed by lochmueller** 2018-12-21 07:47 UTC
