### ISSUE TITLE
Error on upgrading | TYPO3 v 8.7.27

### ISSUE THREAD

**Issue by clausharup** [lochmueller/staticfilecache#172] opened 2019-07-11 08:55 UTC
On upgrading from 6.1.1 to 8.2.2 an error occurs: Call to undefined method SFC\Staticfilecache\Configuration::registerFluidNamespace()

Clearing cache -> everrything works :-)

**Comment by lochmueller** [comment] 2019-07-11 16:20
This is all I can do as extension author: https://github.com/lochmueller/staticfilecache/blob/master/ext_emconf.php#L12
I if found a new idea, I will integegrated it. I close this issue, because solving the problem is simple.

Regards,
Tim

**Closed by lochmueller** 2019-07-11 16:20 UTC
