### ISSUE TITLE
Error 500 system categories

### ISSUE THREAD

**Issue by RicoMahr** [lochmueller/staticfilecache#174] opened 2019-08-01 14:31 UTC
Hello team,

in our current projects we are using SFC and get a strange error after following steps:
- SFC on (normal setup as descriped in the readme)
- visit page (no login in) creates static file in typo3temp
- log in to backend
- edit any CE 
=> ERROR 500 appears on top right corner, no more information available, no log entry
=> now the system categories in it's tab are missing
=> you can't save the CE
- deleting FE-cache or just the SFC folder in typo3temp resolves the problem temporarily

Env
- TYPO3 9.5.8
- SFC 8.2.2 set up as descriped in the readme (backend standard, htaccess adjustments "We found StaticFileCache information in the htaccess file.", boostmode off)
- Tested on Win10 latest, MacOS latest, Ubuntu latest

Someone experiences the same problem? Any help on this available?

**Comment by lochmueller** [comment] 2019-08-01 15:47
Hey @RicoMahr 
could you check if a AJAX call results in the 5xx error?
Regards, Tim

**Comment by RicoMahr** [comment] 2019-08-02 06:37
Hey @lochmueller, yep, in backend one XHR responses with 500: 
"Request URL: https://www.domain.de/typo3/index.php?route=%2Fajax%2Frecord%2Ftree%2FfetchData&token=673c28eaa404be145b98b9cd5720547a5141847b&tableName=tt_content&fieldName=categories&uid=1459&recordTypeValue=mask_services_teaser&dataStructureIdentifier=&flexFormSheetName=&flexFormFieldName=&flexFormContainerName=&flexFormContainerIdentifier=&flexFormContainerFieldName=&flexFormSectionContainerIsNew=&command=edit
Request Method: GET
Status Code: 500 
Remote Address: 153.92.203.223:443
Referrer Policy: no-referrer-when-downgrade"
![insp1](https://user-images.githubusercontent.com/30402023/62349619-966f1300-b500-11e9-9037-62f28d04db35.PNG)
![insp2](https://user-images.githubusercontent.com/30402023/62349624-9a9b3080-b500-11e9-8bd3-5c006b48f749.PNG)

[de.har.txt](https://github.com/lochmueller/staticfilecache/files/3459899/de.har.txt)


Best regards
Rico

**Comment by lochmueller** [comment] 2019-08-02 08:47
Hey Rico,

sounds strange. The StaticFileCache register many things but do not execute thing on general backend requests especially in the page tree. I also saw the "mask_services_teaser" in the URI. Do you check if the problem is related to EXT:mask?

Regards,
Tim

**Comment by RicoMahr** [comment] 2019-08-02 09:57
Hey Tim,

yes mask is installed, but uninstalling it, doesn't solve the problem. I forgot to mention, that, when this happens, the new content element wizards throws a 500 as well. Again clearing FE cache solves it temporarily. There is something with a SFC token ...

Console Output e.g:
![console](https://user-images.githubusercontent.com/30402023/62361957-4dc55300-b51c-11e9-86e3-b9dbbe6634d0.PNG)
![console1](https://user-images.githubusercontent.com/30402023/62362128-9f6ddd80-b51c-11e9-9f65-cf982bb14d42.PNG)
![console2](https://user-images.githubusercontent.com/30402023/62362132-a268ce00-b51c-11e9-873a-3e9a33053e06.PNG)

**Comment by lochmueller** [comment] 2019-08-02 11:31
Hey Rico,
I cannot rebuild this problem in my development box :-/
Do you have some more error reporting (apache error log) to get a information, where the error is?
Regards,
Tim

**Comment by RicoMahr** [comment] 2019-08-02 11:56
Hey Tim,

on our docker setups it works correctly. Both sites are hosted on Mittwald with Performance Plus (OPcache and APCu).

The PHP log "only" throws kinda randomly the same error on different clicks in backend:
`[02-Aug-2019 13:54:17 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function alert() on null in /html/typo3_src/typo3_src-9.5.8/typo3/sysext/core/Classes/Cache/Backend/ApcuBackend.php:139
Stack trace:
#0 /html/typo3_src/typo3_src-9.5.8/typo3/sysext/core/Classes/Cache/Frontend/VariableFrontend.php(61): TYPO3\CMS\Core\Cache\Backend\ApcuBackend->set('ClassSchematas', 'a:206:{s:52:"TY...', Array, NULL)
#1 /html/typo3_src/typo3_src-9.5.8/typo3/sysext/extbase/Classes/Reflection/ReflectionService.php(77): TYPO3\CMS\Core\Cache\Frontend\VariableFrontend->set('ClassSchematas', 'a:206:{s:52:"TY...')
#2 [internal function]: TYPO3\CMS\Extbase\Reflection\ReflectionService->__destruct()
#3 {main}
  thrown in /html/typo3_src/typo3_src-9.5.8/typo3/sysext/core/Classes/Cache/Backend/ApcuBackend.php on line 139
`

**Comment by lochmueller** [comment] 2019-08-02 12:20
Hey Rico,

seems to be a problem with "ApcuBackend". The call of the logger (because the backend could not write into the cache) create this Fatal error. Could you switch from all ApcuBackend to regular DB backend and test if this solve the problem. If this solve the issue, it is a core issue or a problem of the special Mittwald configuration...

PS: Are you at the DeveloperDays in Karlsruhe at the moment?

Regards,
Tim

**Comment by RicoMahr** [comment] 2019-08-02 12:23
Hey Tim,

thanks for the suggestion, i'll try this. My colleague is there. If you want, I can connect you. He knows about this issue. (https://github.com/Micha-sus)

**Comment by lochmueller** [comment] 2019-08-03 09:06
Good idea... I contacted Michael via Slack 👍

**Comment by lochmueller** [comment] 2019-09-10 09:08
Hey @RicoMahr ,
I close this issue. The core version 9.5.9 fix the logging problem. They init the logging in the construct method `AbstractBackend::__construct`. So the error should not apear anymore... but keep in mind, that the caching in your system do not work in the right way (active the logging and check the messages).
Regards,
Tim

**Closed by lochmueller** 2019-09-10 09:08 UTC
