### ISSUE TITLE
sitemap.xml getting cached but not delivered from cache

### ISSUE THREAD

**Issue by MartinH0** [lochmueller/staticfilecache#273] opened 2020-11-02 22:23 UTC
## Bug Report

**Environment**
* **TYPO3 Version**: 10.4.9
* **SFC Version**: 12.0.2
* **PHP Version**: 7.4.11
* **OS**: Unix
* **Composer**: no
* **SFC Settings**: (see below)
* **backendDisplayMode**: both
* **boostMode**: 1
* **cacheTagsEnable**: 0
* **clearCacheForAllDomains**: 1
* **debugHeaders**: 0
* **disableInDevelopment**: 0
* **enableGeneratorBrotli**: 0
* **enableGeneratorGzip**: 1
* **enableGeneratorManifest**: 0
* **enableGeneratorPlain**: 1
* **hashUriInCache**: 0
* **htaccessTemplateName**: EXT:staticfilecache/Resources/Private/Templates/Htaccess.html
* **overrideCacheDirectory**: 
* **rawurldecodeCacheFileName**: 0
* **renameTablesToOtherPrefix**: 0
* **sendCacheControlHeaderRedirectAfterCacheTimeout**: 0
* **sendHttp2PushEnable**: 1
* **sendHttp2PushFileExtensions**: css
* **sendHttp2PushFileLimit**: 10
* **sendHttp2PushLimitToArea**: 
* **useFallbackMiddleware**: 0
* **useReverseUriLengthInPriority**: 1
* **validHtaccessHeaders**: Content-Type,Content-Language,Link,X-SFC-Tags

When I call https://domain.de/sitemap.xml I check the header and can see the SFC header is missing, on the other pages its set correct.

As sitemaps sometimes take long to generate if not cached this can be very valuable for SEO as google would take less time to crawl your page (sitemap) if the content is getting delivered faster.

Maybe this there is just something missing, so .xml files are not getting delivered, but when I run the `boostQueue` command it 100% generates on its own the /sitemap.xml and also shows it as generated under **Cache View** as PID 1

Folder "index.xml" lookes like this:
![sitemap xml Folder](https://user-images.githubusercontent.com/17692860/97926337-3f8b6580-1d63-11eb-9181-6bf18b17c82a.PNG)

Content of the files are also correct. Seems like it is just not getting delivered

**Comment by lochmueller** [comment] 2020-11-03 07:39
Hey @MartinH0 

I tested it on my local maschine and it works great. Any more details for your problem? Do you check if the file is delivered? Could you add headers to the htaccess file and check this in FE. Is mod_headers active? Do you try the Fallback Middleware as tmp solutation?

Regards,
Tim

![Bildschirmfoto 2020-11-03 um 08 36 03](https://user-images.githubusercontent.com/3907126/97959502-c49c6c00-1daf-11eb-8178-84af0589711e.png)
![Bildschirmfoto 2020-11-03 um 08 35 53](https://user-images.githubusercontent.com/3907126/97959505-c5cd9900-1daf-11eb-8751-6dfbf712fa46.png)

**Comment by MartinH0** [comment] 2020-11-03 11:16
As soon as I use Middleware things are changing, but the result is not like expected.
Now it still does not have the neede header and .htaccess looks (in the mod_headers) part exactly the same.

Also `mod_headers` is active.

What changed:
as soon as I turn on moddleware and wipe all cache it somehow changes the sitemap.xml so it does not the xsl file anymore which is styling the sitemap.xml

I have to say I do have implemented a routenhancer which looks like this:

```
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
```

this makes the sitemap.xml appear on domain.tld/sitemap.xml

**Comment by lochmueller** [comment] 2020-11-04 21:36
Hmm... I use the same `PageTypeSuffix` routing configuration without the FallbackMiddleware (if you mean this middleware with "Middleware things") and everything works great. If the cache file exists and the .htaccess file next to the cache file is also right (please double check both), than it is a problem in your root .htaccess file.

Please double check this configuration:
https://github.com/lochmueller/staticfilecache/blob/master/Documentation/Configuration/Htaccess.rst

- Please check "SFC_FULLPATH" in this line "### Begin: StaticFileCache (main) ####"
- Check if your really have no "staticfilecache" cookie!
- Check if "SFC_ROOT" is ok
- Check if there are other non-staticfilecache rules that could effect this

Regards,
Tim

**Comment by lochmueller** [comment] 2020-11-15 13:12
Hey @MartinH0 
any news for this issue? I cannot reproduce this... do you check the points above. Otherwise I will close this issue...
Regards,
Tim

**Closed** 2020-11-18 19:50 UTC
Labels: bug
