### ISSUE TITLE
PHP Warning: rename ... File name too long

### ISSUE THREAD

**Issue by gtedv** [lochmueller/staticfilecache#267] opened 2020-09-14 11:29 UTC
When I clear all caches an error appear like this:

Core: Error handler (BE): PHP Warning:
  rename(/home/strato/http/premium/rid/88/88/88888888/htdocs/typo3cms-9/typo3temp/tx_staticfilecache/http_alt.gt-edv.de_80_1599990067522_1599990067525_1599990067528_1599990067529_1599990067531_1599990067533_1599990067534_1599990067536_1599990067538_1599990067540_1599990067541_1599990067543_1599990067545_1599990067547_1599990067548_1599990067550/,/home/strato/http/premium/rid/88/88/88888888/htdocs/typo3cms-9/typo3temp/tx_staticfilecache/http_alt.gt-edv.de_80_1599990067522_1599990067525_1599990067528_1599990067529_1599990067531_1599990067533_1599990067534_1599990067536_1599990067538_1599990067540_1599990067541_1599990067543_1599990067545_1599990067547_1599990067548_1599990067550_1599990067552/):
  File name too long in
  /mnt/web411/b2/88/88888888/htdocs/typo3cms-9/typo3conf/ext/staticfilecache/Classes/Service/RemoveService.php
  line 75

The website is hosted on a Strato server and the first part of the path is created by the provider. So I can't change it to a shorter one.
Sometimes I have to clear all caches because no further pages will be created in typo3temp/tx_staticfilecache. After that it works again for the current browser session showing the frontend.

**Environment**
* **TYPO3 Version**: 9.5.21
* **SFC Version**: 11.1.7
* **PHP Version**: 7.3.21
* **OS**: Unix
* **Composer**: no
* **SFC Settings**: (see below)
* **backendDisplayMode**: both
* **boostMode**: 0
* **cacheTagsEnable**: 0
* **clearCacheForAllDomains**: 1
* **debugHeaders**: 0
* **disableInDevelopment**: 0
* **enableGeneratorBrotli**: 0
* **enableGeneratorGzip**: 1
* **enableGeneratorManifest**: 0
* **enableGeneratorPlain**: 0
* **hashUriInCache**: 0
* **htaccessTemplateName**: EXT:staticfilecache/Resources/Private/Templates/Htaccess.html
* **overrideCacheDirectory**: 
* **rawurldecodeCacheFileName**: 0
* **renameTablesToOtherPrefix**: 0
* **sendCacheControlHeaderRedirectAfterCacheTimeout**: 0
* **sendHttp2PushEnable**: 0
* **sendHttp2PushFileExtensions**: css,js
* **sendHttp2PushFileLimit**: 10
* **useFallbackMiddleware**: 1
* **useReverseUriLengthInPriority**: 1
* **validHtaccessHeaders**: Content-Type,Content-Language,Link,X-SFC-Tags

**Comment by lochmueller** [comment] 2020-09-14 13:34
Strange... why there is this creazy number behind the port? "1599990067522_1599990067525_1599990067528_1599990067529_1599990067531_1599990067533_1599990067534_1599990067536_1599990067538_1599990067540_1599990067541_1599990067543_1599990067545_1599990067547_1599990067548_1599990067550" It is not the path, right?

**Comment by gtedv** [comment] 2020-09-14 13:43
No, that´s not the path. And I don´t know what generated this numbers.

**Comment by lochmueller** [comment] 2020-09-14 16:29
Hmmm.... looks like the folder are not generated by staticfilecache?! I do not found a code that generate such folders: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/IdentifierBuilder.php#L31

**Comment by gtedv** [comment] 2020-09-15 06:26
I think my posting wasn´t clear enough. Here is the warning text again:

Core: Error handler (BE): PHP Warning:
  rename(**/home/strato/http/premium/rid/12/34/12345678/htdocs/**typo3cms-9/typo3temp/tx_staticfilecache/http_alt.gt-edv.de_80_1600081913768_1600081913771_1600081913774_1600081913776_1600081913779_1600081913782_1600081913787_1600081913789_1600081913791_1600081913793_1600081913794_1600081913796_1600081913798_1600081913799_1600081913801_1600081913803/,/home/strato/http/premium/rid/12/34/12345678/htdocs/typo3cms-9/typo3temp/tx_staticfilecache/http_alt.gt-edv.de_80_1600081913768_1600081913771_1600081913774_1600081913776_1600081913779_1600081913782_1600081913787_1600081913789_1600081913791_1600081913793_1600081913794_1600081913796_1600081913798_1600081913799_1600081913801_1600081913803_1600081913804/):
  File name too long in
  /mnt/web123/b1/12/12345678/htdocs/typo3cms-9/typo3conf/ext/staticfilecache/Classes/Service/RemoveService.php
  line 75

This is an example of the first part from the absolute path, created by Strato: 
/home/strato/http/premium/rid/12/34/12345678/htdocs/

Is it possible to use a relative path instead an absolute one for the rename command? If so it could start at typo3temp and the path would be much shorter.

**Comment by lochmueller** [comment] 2020-09-16 05:35
The problem is not the length of the complete path. The problem is the single folder name:
"http_alt.gt-edv.de_80_1600081913768_1600081913771_1600081913774_1600081913776_1600081913779_1600081913782_1600081913787_1600081913789_1600081913791_1600081913793_1600081913794_1600081913796_1600081913798_1600081913799_1600081913801_1600081913803"

The extension try to rename it to "http_alt.gt-edv.de_80_1600081913768_1600081913771_1600081913774_1600081913776_1600081913779_1600081913782_1600081913787_1600081913789_1600081913791_1600081913793_1600081913794_1600081913796_1600081913798_1600081913799_1600081913801_1600081913803_1600081913804" and this are more characters than 255 and this is not allowed in your filesystem.

There is a rule that check the length in the generation process:
https://github.com/lochmueller/staticfilecache/blob/master/Classes/Cache/Rule/NoLongPathSegment.php#L33

But in the delete process the timestamp will attached, without addional checks. The problem could solved by direct drop the folder in your case. But the basic problem is, why there are so much numbers behind the folder?!?!

Seems like, the folder was renamed before, but never dropped. Perhaps a rights problem, that allow attach the timestamp, but cannot drop the folder?!?! And if you clear the caches everytime a timestamp was attached? The destructor of the RemoveService should finally drop the folder after the rename process: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Service/RemoveService.php#L87

**Comment by gtedv** [comment] 2020-09-16 16:06
I checked again what happens if I clear all caches. The folder http_alt.gt-edv.de_80 disappear immediately, without a renaming before. The warning is shown like before. With the first access to the frontend the folder is created new with the same name and without any timestamp. 
Only in the warning is the name with timestamp shown which is too long.
I think the generation of the timestamp from here 
https://github.com/lochmueller/staticfilecache/blob/master/Classes/Service/RemoveService.php#L74
will be done more than once. 
There could be a bug in the function startting at
https://github.com/lochmueller/staticfilecache/blob/master/Classes/Service/RemoveService.php#L47

The timestamps are for the subdirectories, one for each, but the bug in this function let grow the name of the folder http_alt.gt-edv.de_80.
In Linux/Unix a directory with subfolders can be removed recursive with 'rm -r foldername' . Is it possible also with PHP for the folder on top, in this case http_alt.gt-edv.de_80?

**Comment by gtedv** [comment] 2020-09-16 16:41
It´s not necessary to remove the subfolders. The folder http_alt.gt-edv.de_80 will be removed with its subfolders.

**Comment by lochmueller** [comment] 2020-09-17 06:35
There is a core function that drop the folder: https://github.com/lochmueller/staticfilecache/blob/master/Classes/Service/RemoveService.php#L88 Problem is, that the folder could be very big and the cache clear have to be quick. That is the reason for this process:
- rename folder (very fast)
- truncate DB (very fast)
- finaly remove the folder (slow)

You have to check, why your folder is renamed, but not removed. There are many timestamps in your folder name and it looks like the folder could renamed but the remove process is brocken in your case.

I could not help to solve this because I cannot rebuild this situation.

Regardas,
Tim

**Comment by gtedv** [comment] 2020-09-19 08:10
Ok, thank you. 

Maybe the warning occur only on Strato servers. I think that happend also with older extensions like nc_ctaticfilecache etc. and in older TYPO3 versions, 7.6 etc.

Maybe I try to check the renaming of the folder but its difficult because I haven´t ever seen it before. The folder with the original name disappear immediately if the cache will be flushed.
 
If everything else with staticfilecache works fine I will ignore the warning next time.

Best regards
Torsten

**Comment by lochmueller** [comment] 2020-09-19 11:50
Ok. If you have any news, feel free to send more information. Please keep in mind, that the renaming is NOT the problem. The problem is, that SFC could not delete the folder. And as result, the order get a addional timestamp on each clear cache. So if you try to search for the problem, you have to check why GeneralUtility::rmdir could not remove the folder.

**Comment by gtedv** [comment] 2020-09-21 07:13
Yes, if there is something new I will inform you.

**Comment by lochmueller** [comment] 2020-10-20 15:16
I close this issue. Seams to be a problem on your machine only.
If you found a solution (or a problem in the StaticFileCache integration) please send us more details.

**Closed by lochmueller** 2020-10-20 15:16 UTC
Labels: bug
